const types = {
    REQUEST_DESKS: '@product/REQUEST_DESKS',
    REQUEST_CHAIRS: '@product/REQUEST_CHAIRS',
    REQUEST_LIGHTING: '@product/REQUEST_LIGHTING',
    SET_DESKS: '@product/SET_DESKS',
    SET_CHAIRS: '@product/SET_CHAIRS',
    SET_LIGHTING: '@product/SET_LIGHTING',
    ADD_PRODUCT_TO_CART: '@product/ADD_PRODUCT_TO_CART',
    REMOVE_PRODUCT_FROM_CART: '@product/REMOVE_PRODUCT_FROM_CART',
    REQUEST_PRODUCT: '@product/REQUEST_PRODUCT',
    SET_PRODUCT: '@product/SET_PRODUCT',
    REQUEST_STOCK: '@product/REQUEST_STOCK',
    SET_STOCK: '@product/SET_STOCK',
    SET_TRANSACTION: '@product/SET_TRANSACTION',
    MAKE_PURCHASE: '@product/MAKE_PURCHASE',
    ADD_PRODUCT_QUANTITY: '@product/ADD_PRODUCT_QUANTITY',
    SUB_PRODUCT_QUANTITY: '@product/SUB_PRODUCT_QUANTITY',
    DELETE_PRODUCT: '@product/DELETE_PRODUCT',
    REGISTER_PRODUCT: '@product/REGISTER_PRODUCT',
    SET_ORDERS: '@product/SET_ORDERS',
    REQUEST_NEW_ORDERS: '@product/REQUEST_NEW_ORDERS',
    REQUEST_NEW_ORDERS_USER: '@product/REQUEST_NEW_ORDERS_USER',
    SHIP_ORDER: '@product/SHIP_ORDER',
    REQUEST_OLD_ORDERS: '@product/REQUEST_OLD_ORDERS',
    REQUEST_OLD_ORDERS_USER: '@product/REQUEST_OLD_ORDERS_USER'
};

export default types;